language: node_js

node_js:
  - 6

matrix:
  include:
    - os: linux
      env: NPM_COMMAND=lint
  include:
    - os: linux
      env: NPM_COMMAND=test

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq install g++-4.8 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.8 ; fi

notifications:
  email: false

script: npm run $NPM_COMMAND
after_success: npm run coveralls
